// <auto-generated />
namespace SimpleSiteWithDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class booklet4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(booklet4));
        
        string IMigrationMetadata.Id
        {
            get { return "201605251044532_booklet4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
